language: generic
services:
  - docker

before_install:
  - docker build -t pti4life/angular-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true -it pti4life/angular-ci node_modules/.bin/ng test --karma-config karma.conf.ci.js frontend --code-coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'angular-ci'
  env: 'angularci-env'
  bucket_name: 'elasticbeanstalk-us-east-2-463707494160'
  bucket_path: 'angular-ci'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY