sudo: required
services:
  - docker

before_install:
  - docker build -t pti4life/angular-ci -f Dockerfile.dev .

script:
  - docker run -it pti4life/angular-ci node_modules/.bin/ng test --karma-config karma.conf.ci.js frontend --code-coverage