version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - '/app/node_modules'
      - '.:/app'
  frontend-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9876:9876"
    volumes:
      - '/app/node_modules'
      - '.:/app'
    command: ["/bin/sh", "-c", "node_modules/.bin/ng test --karma-config karma.conf.ci.js frontend"]